### ISSUE TITLE
xhost settings

### ISSUE THREAD

**Issue by nuest** [adrienandrem/interimage-docker#2]
I tried to start the image with UI but ran into some issues. Just to confirm with you: Did you also set `xhost +` before starting the image?

What is the result of `xhost` on your machine?

**Comment by adrienandrem** [comment]
Yes, see: http://courses.neteler.org/fun-docker-grass-gis-software

xhost says: "non-network local connections being added to access control list"

Then docker build and run

**Comment by nuest** [comment]
Thanks!
